version: 2.1

orbs:
  node: circleci/node@5.0.0

commands:
  setup_1:
    description: "checkout, install dependencies"
    steps:
      - checkout
      - node/install-packages

  config_test_1:
    description: "test writing fake firebase service account creds from Circle env vars"
    steps:
      - run: ls -l | awk '{print $5, $9}'
      - run: echo $FAKE_ENV_JSON
      - run: echo $FAKE_ENV_JSON > ./fake_env.json
      - run: ls -l | awk '{print $5, $9}'

  config_test_2:
    description: "test writing fake firebase service account creds from Circle env vars"
    steps:
      - run: ls -l | awk '{print $5, $9}'
      - run: echo $FAKE_ENV_JSON
      - run: touch ./fake_env_file.json
      - run: echo $FAKE_ENV_JSON >> ./fake_env_file.json
      - run: ls -l | awk '{print $5, $9}'

  run_tests_test:
    description: "ooo check; run tests, maybe"
    steps:
        - run: ls -l | awk '{print $5, $9}'
        - run: npm run mocha

jobs:
  circle_setup_test:
    executor:
      name: node/default
      tag: '17.4.0'
    steps:
      - setup_1
      - config_test_1
      - config_test_2
      - run_tests_test

workflows:
  build_test:
    jobs:
      - circle_setup_test
