version: 2.1

parameters:
  TEST_ENV:
    type: string
    default: fake_test_env

orbs:
  node: circleci/node@5.0.0

commands:
  setup_1:
    description: "checkout, install mocha test dependencies"
    steps:
      - checkout
      - node/install-packages
  
  setup_env:
    # define env vars at runtime
    steps:
      - run: echo export TEST_ENV_VAR=\"<< pipeline.parameters.TEST_ENV >>\" >> "$BASH_ENV"
      - run: echo export TEXT_VAR=\"CIRCLE_JOB $CIRCLE_JOB CIRCLE_BRANCH $CIRCLE_BRANCH CIRCLE_BUILD_URL $CIRCLE_BUILD_URL\" >> "$BASH_ENV"

  config_test:
    description: "test writing fake firebase service account creds from Circle env vars"
    steps:
      - run: ls -l | awk '{print $5, $9}'
      - run: echo $FAKE_ENV_JSON > ./fake_env.json
      - run: ls -l | awk '{print $5, $9}'

  run_tests:
    description: "see if creds file exists, run tests"
    steps:
        - run: ls -l | awk '{print $5, $9}'
        - run: npm run mocha

  slack_setup:
    steps:
      - run:
          name: write slack payload to file
          command: |
            echo '{"TEXT": "'"$TEXT_VAR"'", "TEST_ENV": "'"$TEST_ENV_VAR"'"}'
            echo '{"TEST_ENV": "'"$TEST_ENV_VAR"'", "TEXT": "'"$TEXT_VAR"'"}' > payload.json

  slack_post:
    steps:
      - run:
          name: cat payload.json
          command: cat payload.json
      - run: 
          name: post payload.json to slack webhook url
          command: |
            curl -X POST -H 'Content-type: application/json' --data @payload.json $TEST_WEBHOOK_NOTIF_URL

  # slack_2:
  #   description: "Test out the slack spambot, part 2"
  #   steps:
  #     - run: echo 'example slack_2 text TEST_ENV_VAR $TEST_ENV_VAR TEXT_VAR $TEXT_VAR'
  #     - run:
  # #         #name: Notify ir_pipeline_team_test_notifs Slack channel
  #         name: slack_2 -d TEXT as "example slack_2 text TEST_ENV_VAR $TEST_ENV_VAR TEXT_VAR $TEXT_VAR"
  #         when: always #on_success
  #         command: |
  #             curl -X POST "$TEST_WEBHOOK_NOTIF_URL" \
  #             -H 'Content-type: application/json' \
  #             -d '{ "TEXT": "example slack_2 text TEST_ENV_VAR $TEST_ENV_VAR TEXT_VAR $TEXT_VAR" }'
  # slack_3:
  #   description: "Test out the slack spambot, part 2 the 2nd"
  #   steps:
  #     - run: echo "$TEXT"
  #     - run: |
  #         curl -X POST "$TEST_WEBHOOK_NOTIF_URL" \
  #         -H 'Content-type: application/json' \
  #         -d { "TEXT": "$TEXT" }


jobs:
  circle_config_test: 
    executor:
      name: node/default
      tag: '16.16.0'
    steps:
      - setup_env
      - slack_setup
      - slack_post

workflows:
  build_test:
    jobs:
      - circle_config_test
